
export const array = [
    '(child noises in the background)',
    'Hello, hello?',
    'i need to jump in another call',
    'can everyone go on mute',
    'could you please get closer the mic',
    '(load painful echo / feedback)',
    'next slide please.',
    'can we take this offline?',
    'is ____ on the call?',
    'could you share this slides afterwards?',
    'can somebody grant presenter rights?',
    'can you email that everyone?',
    'sorry, i had problems loging in',
    '(animal noises in the background)',
    'sorry, i didnt found the conference id',
    'i was having connection issues',
    'i ll have to get back to you',
    'who just joined?',
    'sorry something with my eelendof',
    'do you see my screen?',
    'lets wait for ___?',
    'You will send the minutes?',
    'sorry, I was on mute,',
    'can you repeat please?',
    'please try again',
  ];